### ISSUE TITLE
blank screen in npm start

### ISSUE THREAD

**Issue by ghost** [acjim/AcmacsDesktop#450]
Hi, I am getting following error with blank page when I run `npm start`. Any help will be appreciated. 

```
Binits-MacBook-Pro:AcmacsDesktop binitlamichhane$ npm start

> AcmacsDesktop@1.1.0 start /Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop
> nw src

[5454:0304/133156:WARNING:shell_main_delegate.cc(231)] en-AU.pak file not found.
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[5455:0304/133156:WARNING:shell_main_delegate.cc(231)] en-AU.pak file not found.
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[5456:0304/133156:WARNING:shell_main_delegate.cc(231)] en-AU.pak file not found.
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[5457:0304/133156:WARNING:shell_main_delegate.cc(231)] en-AU.pak file not found.
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[5454:0304/133156:ERROR:nw_shell.cc(336)] Error: [$injector:unpr] Unknown provider: $$MapProvider <- $$Map <- $$animateQueue <- $animate <- $compile <- $$animateQueue
http://errors.angularjs.org/1.4.9/$injector/unpr?p0=%24%24MapProvider%20%3C-%20%24%24Map%20%3C-%20%24%24animateQueue%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24%24animateQueue
    at file:///Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop/src/bower_components/angular/angular.js:68:12
    at file:///Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop/src/bower_components/angular/angular.js:4346:19
    at Object.getService [as get] (file:///Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop/src/bower_components/angular/angular.js:4494:39)
    at file:///Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop/src/bower_components/angular/angular.js:4351:45
    at getService (file:///Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop/src/bower_components/angular/angular.js:4494:39)
    at Object.invoke (file:///Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop/src/bower_components/angular/angular.js:4526:13)
    at file:///Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop/src/bower_components/angular/angular.js:4352:37
    at getService (file:///Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop/src/bower_components/angular/angular.js:4494:39)
    at Object.invoke (file:///Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop/src/bower_components/angular/angular.js:4526:13)
    at file:///Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop/src/bower_components/angular/angular.js:4352:37
[5454:0304/133156:INFO:CONSOLE(4499)] "Uncaught Error: [$injector:unpr] Unknown provider: $$MapProvider <- $$Map <- $$animateQueue <- $animate <- $compile <- $$animateQueue
http://errors.angularjs.org/1.4.9/$injector/unpr?p0=%24%24MapProvider%20%3C-%20%24%24Map%20%3C-%20%24%24animateQueue%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24%24animateQueue", source: file:///Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop/src/bower_components/angular/angular.js (4499)
```
```

**Comment by rohankoid** [comment]
@bineetuwa did you get any error when running

`npm install`

Which version of node.js and npm are you using?

**Comment by ghost** [comment]
`npm install` gives: 
```
> AcmacsDesktop@1.1.0 postinstall /Users/binitlamichhane/Documents/Bioinfo_tools/AcmacsDesktop
> (cd src && ../node_modules/.bin/bower install)
```

The version of node.js and npm is 7.7.1. I am doing this in MacOS and installed them using brew.
